---
- name: Check current process_exporter version
  failed_when: false
  changed_when: false
  register: prometheus_process_exporter_bin_stat
  ansible.builtin.stat:
    path: "{{ prometheus_process_exporter_bin_path }}"

- name: Check current process_exporter version
  when: prometheus_process_exporter_bin_stat.stat.exists
  failed_when: false
  changed_when: false
  register: prometheus_process_exporter_version_check
  ansible.builtin.command: "{{ prometheus_process_exporter_bin_path }} --version"

- name: Stop process_exporter
  when: prometheus_process_exporter_bin_stat.stat.exists
  ignore_errors: true
  ansible.builtin.service:
    name: "{{ prometheus_process_exporter_name }}"
    state: stopped
    enabled: false

- name: Download and decompress process_exporter into temporary location
  when:
    not prometheus_process_exporter_bin_stat.stat.exists
    or
    prometheus_process_exporter_version_check.stdout is not defined
    or
    prometheus_process_exporter_version not in prometheus_process_exporter_version_check.stdout
  ansible.builtin.unarchive:
    src: "{{ prometheus_process_exporter_download_url | replace(' ', '') }}"
    dest: /tmp
    remote_src: true

- name: Move process_exporter binary into place
  when:
    not prometheus_process_exporter_bin_stat.stat.exists
    or
    prometheus_process_exporter_version_check.stdout is not defined
    or
    prometheus_process_exporter_version not in prometheus_process_exporter_version_check.stdout
  ansible.builtin.copy:
    src: /tmp/{{ prometheus_process_exporter_name }}-{{ prometheus_process_exporter_version }}.linux-{{ prometheus_process_exporter_arch }}/{{ prometheus_process_exporter_name }}
    dest: "{{ prometheus_process_exporter_bin_path }}"
    mode: "0755"
    remote_src: true

- name: Create process_exporter user
  ansible.builtin.user:
    name: "{{ prometheus_process_exporter_name }}"
    shell: /sbin/nologin
    state: present

- name: Create process_exporter systemd unit file
  when: ansible_service_mgr == "systemd"
  ansible.builtin.template:
    src: exporter.service.j2
    dest: /etc/systemd/system/{{ prometheus_process_exporter_name }}.service
    mode: "0644"
    owner: root
    group: root

- name: Create process_exporter sysv init file
  when: ansible_service_mgr == "sysvinit"
  ansible.builtin.template:
    src: exporter.j2
    dest: /etc/init.d/{{ prometheus_process_exporter_name }}
    mode: "0644"
    owner: root
    group: root

# - name: "sysvinit enable"
#   ansible.builtin.command:
#     cmd: "chkconfig {{ prometheus_process_exporter_name }} on"
#   when: ansible_service_mgr == "sysvinit"

- name: Systemd daemon-reload
  when: ansible_service_mgr == "systemd"
  ansible.builtin.systemd:
    daemon_reload: true

- name: Ensure process_exporter is started
  ansible.builtin.service:
    name: "{{ prometheus_process_exporter_name }}"
    enabled: true
    state: started
