---
- name: stop process_exporter container
  community.docker.docker_container:
    name: process_exporter
    state: stopped
  ignore_errors: true

- name: remove process_exporter container
  community.docker.docker_container:
    name: process_exporter
    state: absent
  ignore_errors: true
